{
  try {
    executor.submit(backupTask);
  }
 catch (  RejectedExecutionException e) {
    LOGGER.debug("Rejecting while another backup process is already running.");
  }
}
